modLoader = "javafml"
loaderVersion = "[24,)"
license = "https://github.com/Jeryn99/Weeping-Angels/blob/mc/1.20.1/LICENSE"
issueTrackerURL = "https://github.com/Jeryn99/Weeping-Angels/issues"
[[mods]]
displayURL = "https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod"
logoFile = "weeping_angels.png"
credits = "Suff, 50ap5ud5, Ed, Violet, Rolf, Nictogen, Lukas, ShadowBolt, DisasterGae, DocArcane, Dhi_awesome, ConnorDawn, Classic, The_MidFord, Hiveius"
authors = "Jeryn99, 50ap5ud5"
itemIcon = "weeping_angels:timey_wimey_detector"
modId = "weeping_angels"
version = "1"
displayName = "Weeping Angels"
updateJSONURL = "https://mc-api.craig.software/update?mod=weeping_angels" #optional
description = '''
Mod that adds the terrifying Weeping Angel creatures to Minecraft || Originally made for ModJam 5'''
[[dependencies.weeping_angels]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.weeping_angels]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19, ]"
ordering = "NONE"
side = "BOTH"