plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "me.shedaniel.unified-publishing" version "0.1.+"
    id "net.darkhax.curseforgegradle" version "1.1.+"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "weeping_angels-common.mixins.json"
        mixinConfig "weeping_angels.mixins.json"

        dataGen {
            mod "weeping_angels"
        }
    }

    runs {
        data {
            programArgs "--existing", project(":common").file("src/main/resources/").absolutePath
        }
    }
}

unifiedPublishing {
    project {
        displayName = "[Forge] Weeping Angels - v$rootProject.minecraft_version-$project.version"
        releaseType = "release"
        changelog = new File("${rootProject.projectDir}/changelog.html").text
        gameVersions = ["1.20", "1.20.1"]
        mainPublication tasks.remapJar
        gameLoaders = ["forge"]
        relations {

        }

        var MODRINTH_TOKEN = project.findProperty("modrinth") ?: System.getenv("modrinth") ?: ""
        if (MODRINTH_TOKEN != "") {
            modrinth {
                token = MODRINTH_TOKEN
                id = "TEzJJY7H"
                version = "$project.version+$project.name"
            }
        }
    }
}

// CurseForge upload - unifiedPublishing's CurseGradle is archived and can't send the required environment tag.
var curseToken = project.findProperty("curseforge") ?: System.getenv("curseforge") ?: ""

tasks.register("publishCurseForge", net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    group = "upload"
    disableVersionDetection()
    onlyIf { curseToken != "" }

    apiToken = curseToken

    def mainFile = upload("291249", tasks.remapJar)
    mainFile.changelogType = "html"
    mainFile.changelog = new File("${rootProject.projectDir}/changelog.html")
    mainFile.releaseType = "release"
    mainFile.addGameVersion("1.20", "1.20.1")
    mainFile.addJavaVersion("Java 17")
    mainFile.addModLoader("Forge")
    mainFile.addEnvironment("Client", "Server")
}



configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"
    modCompileOnlyApi "curse.maven:mc-vr-api-591092:4648734"
    modApi "curse.maven:architectury-api-419699:5137938"


    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "weeping_angels.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = 'forge'
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

sourceSets.main.resources {
    srcDir project(":common").file("src/generated/resources").absolutePath
}


components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}