# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 4 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        stale-issue-message: 'This issue has been marked as stale due to inactivity. If this is still a relevant issue, please comment or take action to prevent it from being closed.'
        stale-pr-message: 'This pull request has been marked as stale due to inactivity. If this is still a relevant change, please address any outstanding feedback or merge conflicts.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
